name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'manifests/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Backend - go vet
        working-directory: ./backend
        run: |
          go mod tidy
          go vet ./...

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Frontend - lint
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint

  build-and-push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker CLI
        run: |
          apt-get update && apt-get install -y docker.io

      - name: Login to Gitea Registry
        run: |
          echo "${{ secrets.REGISTRY_PASSWORD }}" | docker login gitea.azizedursun.com -u "${{ secrets.REGISTRY_USER }}" --password-stdin

      - name: Build and push backend
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build -t gitea.azizedursun.com/azize-projects/fsdevops-backend:${SHORT_SHA} \
                       -t gitea.azizedursun.com/azize-projects/fsdevops-backend:latest \
                       ./backend
          docker push gitea.azizedursun.com/azize-projects/fsdevops-backend:${SHORT_SHA}
          docker push gitea.azizedursun.com/azize-projects/fsdevops-backend:latest

      - name: Build and push frontend
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build --build-arg NEXT_PUBLIC_API_URL=https://api.devops.azizedursun.com \
                       -t gitea.azizedursun.com/azize-projects/fsdevops-frontend:${SHORT_SHA} \
                       -t gitea.azizedursun.com/azize-projects/fsdevops-frontend:latest \
                       ./frontend
          docker push gitea.azizedursun.com/azize-projects/fsdevops-frontend:${SHORT_SHA}
          docker push gitea.azizedursun.com/azize-projects/fsdevops-frontend:latest

  update-manifests:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update image tags in deployment manifest
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          sed -i "s|gitea.azizedursun.com/azize-projects/fsdevops-backend:.*|gitea.azizedursun.com/azize-projects/fsdevops-backend:${SHORT_SHA}|" manifests/deployment.yaml
          sed -i "s|gitea.azizedursun.com/azize-projects/fsdevops-frontend:.*|gitea.azizedursun.com/azize-projects/fsdevops-frontend:${SHORT_SHA}|" manifests/deployment.yaml

      - name: Commit and push manifest update
        run: |
          git config user.name "Gitea Actions"
          git config user.email "actions@gitea.azizedursun.com"
          git add manifests/deployment.yaml
          git diff --cached --quiet && echo "Manifest zaten guncel, degisiklik yok" && exit 0
          git commit -m "ci: image tag guncelle ($(echo ${{ github.sha }} | cut -c1-7))"
          git push origin main
