#!/bin/bash

# DevOps Journey - Quick Setup Script
# Run this on your server after cloning the repo

set -e

echo "======================================"
echo "DevOps Journey - Setup Script"
echo "======================================"
echo ""

# Get server IP
SERVER_IP=$(hostname -I | awk '{print $1}')
echo "Detected Server IP: $SERVER_IP"
echo ""

# Check if .env exists
if [ -f .env ]; then
    echo ".env file already exists. Skipping creation."
    read -p "Do you want to recreate it? (y/N): " recreate
    if [ "$recreate" != "y" ] && [ "$recreate" != "Y" ]; then
        echo "Keeping existing .env file."
    else
        rm .env
    fi
fi

# Create .env if it doesn't exist
if [ ! -f .env ]; then
    echo "Creating .env file..."

    # Generate JWT secret
    JWT_SECRET=$(openssl rand -base64 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

    # Generate DB password
    DB_PASSWORD=$(openssl rand -base64 16 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)

    cat > .env << EOF
# Generated by setup.sh on $(date)
ENVIRONMENT=development
NODE_ENV=development

# Server
SERVER_IP=${SERVER_IP}

# Database
DB_USER=postgres
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=devops_journey

# Backend
ALLOW_ORIGINS=http://localhost:3000,http://${SERVER_IP}:3000

# JWT (auto-generated)
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRATION_HOURS=24

# Frontend API URL
NEXT_PUBLIC_API_URL=http://${SERVER_IP}:8080

# SMTP (configure later)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASSWORD=
SMTP_FROM=
EOF

    echo ".env file created successfully!"
    echo ""
fi

echo "======================================"
echo "Starting Docker Compose..."
echo "======================================"

# Build and start
docker compose up -d --build

echo ""
echo "======================================"
echo "Setup Complete!"
echo "======================================"
echo ""
echo "Access your application:"
echo "  Frontend: http://${SERVER_IP}:3000"
echo "  Backend:  http://${SERVER_IP}:8080"
echo "  API Docs: http://${SERVER_IP}:8080/health"
echo ""
echo "Default admin credentials:"
echo "  Email:    admin@example.com"
echo "  Password: (set via DEFAULT_ADMIN_PASSWORD env var, or auto-generated - check backend logs)"
echo ""
echo "IMPORTANT: Set a strong password via DEFAULT_ADMIN_PASSWORD env var!"
echo ""
echo "View logs: docker compose logs -f"
echo "Stop:      docker compose down"
echo ""
